# test this file with
#   goreleaser release --config goreleaser.yml --clean --snapshot
version: 2
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/jpillora/chisel/share.BuildVersion={{.Version}}
    flags:
      - -trimpath
    gobinary: "garble-custom"
    goos:
      - linux
      - darwin
      - windows
      - openbsd
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - ppc64
      - ppc64le
      - mips
      - mipsle
      - mips64
      - mips64le
      - s390x
    goarm:
      - "5"
      - "6"
      - "7"
    gomips:
      - hardfloat
      - softfloat
    ignore:
      # https://github.com/golang/go/issues/70705
      - goos: windows
        goarch: arm
nfpms:
  - maintainer: "https://github.com/jpillora"
    formats:
      - deb
      - rpm
      - apk
archives:
  - formats:
      - gz
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - none*
release:
  draft: true
  prerelease: auto
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
